DIR:
  Origin: "./data/original_data"
  Score: "./data/scores"
  Result: "./data/results"
  Weight: "./model_weights"

MODEL:
  MobileCLIP: True
  OpenCLIP: True
  EvaCLIP: True
  MetaCLIP: True
  BlipITC: True

WEIGHT:
  Consensus_Score: 0
  CLIP_Score: 1

THRESH:
  Short_Threshold: 0.0000000000000000000001
